[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build]
  command = "npm install --prefix frontend && CI=false npm run build --prefix frontend"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 