[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build]
  command = "cd frontend && npm install && CI=false ./node_modules/.bin/react-scripts build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 